Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
##Â import ete3 using if you have conda: 
##Â conda install -c etetoolkit ete3
## otherwise try: pip install ete3 pyQT5
import ete3 as ete
##Â Define the tree
T = ("a",(("b","c"),("d","e")))

t = ete.Tree(str(T)+";")

ts = ete.TreeStyle()
#ts.rotation = 90
ts.scale = 90
ts.branch_vertical_margin = 50 # 10 pixels between adjacent branches
ts.show_leaf_name = False #

nstyle = ete.NodeStyle()
nstyle["shape"] = "square"
nstyle["size"] = 20
nstyle["fgcolor"] = "orange"

for n in t.traverse():
    n.set_style(nstyle)

for node in t.iter_leaves():
    node.add_face(ete.AttrFace("name", fsize=20), column=0)  
    
t.render("%%inline", tree_style = ts)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-7-0fffa760194d>[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0;31m##Â conda install -c etetoolkit ete3[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;31m## otherwise try: pip install ete3 pyQT5[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0;32mimport[0m [0mete3[0m [0;32mas[0m [0mete[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0;31m##Â Define the tree[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m [0mT[0m [0;34m=[0m [0;34m([0m[0;34m"a"[0m[0;34m,[0m[0;34m([0m[0;34m([0m[0;34m"b"[0m[0;34m,[0m[0;34m"c"[0m[0;34m)[0m[0;34m,[0m[0;34m([0m[0;34m"d"[0m[0;34m,[0m[0;34m"e"[0m[0;34m)[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'ete3'
ModuleNotFoundError: No module named 'ete3'

