Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# load an image
import imageio as imio
colored_image = imio.imread('lena.png')
n = 220
image = np.sum(colored_image*[0.21, 0.72 ,0.07,0],axis=-1)
plt.figure(figsize = (10,10))
plt.subplot(1,2,1)
plt.gray()
cropped = image[n:n+64,n:n + 64]
plt.title(" Grey Level Image " + str(np.shape(cropped)))

plt.imshow(cropped)
print(np.mean(cropped),np.std(cropped),(np.min(cropped)))
print(image.shape)
image0 = np.copy(image)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-2-b34487702f6e>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# load an image[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;32mimport[0m [0mimageio[0m [0;32mas[0m [0mimio[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0mcolored_image[0m [0;34m=[0m [0mimio[0m[0;34m.[0m[0mimread[0m[0;34m([0m[0;34m'lena.png'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0mn[0m [0;34m=[0m [0;36m220[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mimage[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0msum[0m[0;34m([0m[0mcolored_image[0m[0;34m*[0m[0;34m[[0m[0;36m0.21[0m[0;34m,[0m [0;36m0.72[0m [0;34m,[0m[0;36m0.07[0m[0;34m,[0m[0;36m0[0m[0;34m][0m[0;34m,[0m[0maxis[0m[0;34m=[0m[0;34m-[0m[0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/imageio/core/functions.py[0m in [0;36mimread[0;34m(uri, format, **kwargs)[0m
[1;32m    263[0m [0;34m[0m[0m
[1;32m    264[0m     [0;31m# Get reader and read first[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 265[0;31m     [0mreader[0m [0;34m=[0m [0mread[0m[0;34m([0m[0muri[0m[0;34m,[0m [0mformat[0m[0;34m,[0m [0;34m"i"[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    266[0m     [0;32mwith[0m [0mreader[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    267[0m         [0;32mreturn[0m [0mreader[0m[0;34m.[0m[0mget_data[0m[0;34m([0m[0;36m0[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/imageio/core/functions.py[0m in [0;36mget_reader[0;34m(uri, format, mode, **kwargs)[0m
[1;32m    170[0m [0;34m[0m[0m
[1;32m    171[0m     [0;31m# Create request object[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 172[0;31m     [0mrequest[0m [0;34m=[0m [0mRequest[0m[0;34m([0m[0muri[0m[0;34m,[0m [0;34m"r"[0m [0;34m+[0m [0mmode[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    173[0m [0;34m[0m[0m
[1;32m    174[0m     [0;31m# Get format[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/imageio/core/request.py[0m in [0;36m__init__[0;34m(self, uri, mode, **kwargs)[0m
[1;32m    122[0m [0;34m[0m[0m
[1;32m    123[0m         [0;31m# Parse what was given[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 124[0;31m         [0mself[0m[0;34m.[0m[0m_parse_uri[0m[0;34m([0m[0muri[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    125[0m [0;34m[0m[0m
[1;32m    126[0m         [0;31m# Set extension[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/imageio/core/request.py[0m in [0;36m_parse_uri[0;34m(self, uri)[0m
[1;32m    258[0m                 [0;31m# Reading: check that the file exists (but is allowed a dir)[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    259[0m                 [0;32mif[0m [0;32mnot[0m [0mos[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0mexists[0m[0;34m([0m[0mfn[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 260[0;31m                     [0;32mraise[0m [0mFileNotFoundError[0m[0;34m([0m[0;34m"No such file: '%s'"[0m [0;34m%[0m [0mfn[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    261[0m             [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    262[0m                 [0;31m# Writing: check that the directory to write to does exist[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: No such file: '/home/runner/work/M2-SIS-signal/M2-SIS-signal/TD/TD5/lena.png'
FileNotFoundError: No such file: '/home/runner/work/M2-SIS-signal/M2-SIS-signal/TD/TD5/lena.png'

